# all options https://taplo.tamasfe.dev/configuration/formatter-options.html

# global rules
[formatting]
reorder_arrays = true
inline_table_expand = false
array_auto_expand = true
array_auto_collapse = false
indent_string = "	"         # tab

[[rule]]
include = ["Cargo.toml"]
keys = ["workspace.dependencies"]

[rule.formatting]
reorder_keys = true
