//! GPU golden-vector tests: the GPU mining kernel and its shader-level Poseidon2
//! implementation must produce byte-identical results to the canonical CPU
//! implementation (pow_core -> qpow-math -> qp-poseidon-core).
//!
//! These tests require a GPU; they skip gracefully when no adapter is available.
//!
//! Golden vectors generated by examples/gen_golden.rs using the canonical
//! CPU implementation. Regenerate if the hash construction ever changes.

use engine_cpu::{EngineStatus, MinerEngine, Range};
use engine_gpu::{precompute_header_state, GpuEngine};
use pow_core::{hash_from_nonce, JobContext};
use primitive_types::U512;
use std::sync::OnceLock;

pub struct GoldenCase {
    pub header_hex: &'static str,
    pub nonce: u64,
    pub hash_hex: &'static str,
}

pub const GOLDEN_CASES: &[GoldenCase] = &[
    GoldenCase {
        header_hex: "0000000000000000000000000000000000000000000000000000000000000000",
        nonce: 0,
        hash_hex: "8e64e3d8e0f38f882e8501f9e525df0a95d2e91e9cfc32c9248d756fb07780e2f8fdca2c5a54441e6fcd8d774a5f6aae72f36d1c76bc19f691a0d4f6c607e8cc",
    },
    GoldenCase {
        header_hex: "0101010101010101010101010101010101010101010101010101010101010101",
        nonce: 123456789,
        hash_hex: "715331a49bffbb8c0a42935113041b6d9d17d64952136b7a533627cf6ce280be17a8d61c656543159c68332fb64ab7fe5ec396bb80b71f219ee282ed661a0522",
    },
    GoldenCase {
        header_hex: "abababababababababababababababababababababababababababababababab",
        nonce: 18446744073709551615,
        hash_hex: "4933afa670ead2a3e350f9d1a3fda366c85fe6f4bde4746d6e934860a157c658aa69949ec4be51d6b05e7e9ca9dbfc496c1cde141c75501cb5d7778e18f0c193",
    },
    GoldenCase {
        header_hex: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
        nonce: 987654321,
        hash_hex: "c4e198c0c86b117719a86d039d4ee239d2484161af628e34639943338d066a2a140d9cf9c51da80625cdc4d6b8d33513d9bed3faa3f164628d0472d1b9aca392",
    },
    GoldenCase {
        header_hex: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        nonce: 42,
        hash_hex: "d637170b8aa94e2d020ae5ccf96149e338cbb5185623f30ec8df4df6497e72f78f9b43cf2475894a4e9d9da8d0e97092f50a8ac0667b247d4c3ccd96194f64d4",
    },
    GoldenCase {
        header_hex: "0707070707070707070707070707070707070707070707070707070707070707",
        nonce: 1099511627776,
        hash_hex: "8316c75199697e0a7315def7b4b25038a53403cbb3a6c7f43ba65705cab02057fb30dfdf3e2a663808924035ec77fa3d4223ec9044e65b9fb9bb7313813f6614",
    },
];

fn decode_header(case: &GoldenCase) -> [u8; 32] {
    hex::decode(case.header_hex).unwrap().try_into().unwrap()
}

fn decode_hash(case: &GoldenCase) -> [u8; 64] {
    hex::decode(case.hash_hex).unwrap().try_into().unwrap()
}

fn golden_hash_u512(case: &GoldenCase) -> U512 {
    U512::from_big_endian(&decode_hash(case))
}

/// Shared engine: GPU + pipeline init is slow, so do it once per test binary.
static ENGINE: OnceLock<Option<GpuEngine>> = OnceLock::new();

fn shared_engine() -> Option<&'static GpuEngine> {
    ENGINE
        .get_or_init(|| GpuEngine::try_new(1_000_000, 0, false).ok())
        .as_ref()
}

/// Mine the exact single nonce of each golden case through the full engine
/// stack (host header precompute + shader) and compare against golden hashes.
#[test]
fn golden_mining_kernel_full_stack() {
    let Some(engine) = shared_engine() else {
        eprintln!("no GPU adapter, skipping golden_mining_kernel_full_stack");
        return;
    };
    let cancel = engine_cpu::AtomicBoolCancelCheck(&std::sync::atomic::AtomicBool::new(false));

    for case in GOLDEN_CASES {
        let ctx = JobContext::new(decode_header(case), U512::from(1u64));
        let nonce = U512::from(case.nonce);
        let result = engine.search_range(
            &ctx,
            Range {
                start: nonce,
                end: nonce,
            },
            &cancel,
        );
        let EngineStatus::Found { candidate, .. } = result else {
            panic!(
                "golden case nonce {}: engine did not find the nonce",
                case.nonce
            );
        };
        assert_eq!(candidate.nonce, nonce, "nonce mismatch");
        assert_eq!(
            candidate.hash,
            golden_hash_u512(case),
            "GPU hash mismatch for golden case (header {}..., nonce {})",
            &case.header_hex[..16],
            case.nonce
        );
        assert_eq!(candidate.work, nonce.to_big_endian());
    }
    GpuEngine::clear_worker_resources();
}

/// Valid-seal semantics: a nonce whose hash is above the target must be
/// rejected (range exhausts), and accepted when the target covers it.
/// Exercises the first-squeeze comparison shortcut in the kernel.
#[test]
fn seal_accept_reject_against_target() {
    let Some(engine) = shared_engine() else {
        eprintln!("no GPU adapter, skipping seal_accept_reject_against_target");
        return;
    };
    let cancel = engine_cpu::AtomicBoolCancelCheck(&std::sync::atomic::AtomicBool::new(false));
    let case = &GOLDEN_CASES[1];
    let hash = golden_hash_u512(case);
    let nonce = U512::from(case.nonce);

    // Target = 2*hash => hash < target => must be found.
    let easy_difficulty = U512::MAX / (hash.saturating_mul(U512::from(2u64))).max(U512::from(1u64));
    let ctx = JobContext::new(decode_header(case), easy_difficulty.max(U512::from(1u64)));
    assert!(hash < ctx.target, "test setup: hash must be below target");
    let result = engine.search_range(
        &ctx,
        Range {
            start: nonce,
            end: nonce,
        },
        &cancel,
    );
    assert!(
        matches!(result, EngineStatus::Found { .. }),
        "valid seal was rejected"
    );

    // Target = hash/2 => hash > target => must be rejected.
    let hard_difficulty = U512::MAX / (hash / U512::from(2u64)).max(U512::from(1u64));
    let ctx = JobContext::new(decode_header(case), hard_difficulty);
    assert!(hash >= ctx.target, "test setup: hash must be above target");
    let result = engine.search_range(
        &ctx,
        Range {
            start: nonce,
            end: nonce,
        },
        &cancel,
    );
    assert!(
        matches!(result, EngineStatus::Exhausted { .. }),
        "invalid seal was accepted"
    );
    GpuEngine::clear_worker_resources();
}

/// Randomized CPU-vs-GPU cross-check: for random headers and nonces, the GPU
/// kernel result must equal the canonical CPU hash.
#[test]
fn cpu_gpu_cross_check_random() {
    use rand::{RngCore, SeedableRng};

    let Some(engine) = shared_engine() else {
        eprintln!("no GPU adapter, skipping cpu_gpu_cross_check_random");
        return;
    };
    let cancel = engine_cpu::AtomicBoolCancelCheck(&std::sync::atomic::AtomicBool::new(false));
    let mut rng = rand_chacha::ChaCha8Rng::seed_from_u64(0xC0FFEE);

    for i in 0..24 {
        let mut header = [0u8; 32];
        rng.fill_bytes(&mut header);
        let nonce = U512::from(rng.next_u64());
        let ctx = JobContext::new(header, U512::from(1u64));

        let expected = hash_from_nonce(&ctx, nonce);
        let result = engine.search_range(
            &ctx,
            Range {
                start: nonce,
                end: nonce,
            },
            &cancel,
        );
        let EngineStatus::Found { candidate, .. } = result else {
            panic!("iteration {i}: engine did not find nonce");
        };
        assert_eq!(candidate.hash, expected, "iteration {i}: GPU != CPU hash");
    }
    GpuEngine::clear_worker_resources();
}

// ---------------------------------------------------------------------------
// Shader-level golden tests (direct WGSL harness around mining.wgsl functions)
// ---------------------------------------------------------------------------

struct ShaderHarness {
    device: wgpu::Device,
    queue: wgpu::Queue,
}

fn shader_harness() -> Option<ShaderHarness> {
    let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
        backends: wgpu::Backends::PRIMARY,
        ..Default::default()
    });
    let adapter = futures::executor::block_on(
        instance.request_adapter(&wgpu::RequestAdapterOptions::default()),
    )
    .ok()?;
    let (device, queue) =
        futures::executor::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
            label: Some("golden-test"),
            required_features: wgpu::Features::empty(),
            required_limits: wgpu::Limits::default(),
            ..Default::default()
        }))
        .ok()?;
    Some(ShaderHarness { device, queue })
}

impl ShaderHarness {
    fn run_hash_shader(&self, entry_wgsl: &str, buffers: &[(u32, wgpu::Buffer, bool)]) -> Vec<u32> {
        // buffers: (binding, buffer, is_output). Returns contents of the output buffer.
        let shader = self
            .device
            .create_shader_module(wgpu::ShaderModuleDescriptor {
                label: Some("golden-harness"),
                source: wgpu::ShaderSource::Wgsl(entry_wgsl.into()),
            });
        let pipeline = self
            .device
            .create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: None,
                layout: None,
                module: &shader,
                entry_point: Some("main"),
                compilation_options: Default::default(),
                cache: None,
            });
        let bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &pipeline.get_bind_group_layout(0),
            entries: &buffers
                .iter()
                .map(|(binding, buf, _)| wgpu::BindGroupEntry {
                    binding: *binding,
                    resource: buf.as_entire_binding(),
                })
                .collect::<Vec<_>>(),
        });

        let (_, out_buf, _) = buffers
            .iter()
            .find(|(_, _, is_out)| *is_out)
            .expect("output buffer");
        let staging = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: out_buf.size(),
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
        {
            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: None,
                timestamp_writes: None,
            });
            cpass.set_pipeline(&pipeline);
            cpass.set_bind_group(0, &bind_group, &[]);
            cpass.dispatch_workgroups(GOLDEN_CASES.len() as u32, 1, 1);
        }
        encoder.copy_buffer_to_buffer(out_buf, 0, &staging, 0, out_buf.size());
        self.queue.submit(Some(encoder.finish()));

        let slice = staging.slice(..);
        let (tx, rx) = futures::channel::oneshot::channel();
        slice.map_async(wgpu::MapMode::Read, move |r| tx.send(r).unwrap());
        self.device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .unwrap();
        futures::executor::block_on(rx)
            .expect("map channel dropped")
            .expect("buffer map failed");
        let data = slice.get_mapped_range();
        let words: Vec<u32> = bytemuck::cast_slice(&data).to_vec();
        drop(data);
        let _ = slice;
        staging.unmap();
        words
    }
}

fn mk_storage(device: &wgpu::Device, data: &[u32], writable: bool) -> wgpu::Buffer {
    use wgpu::util::DeviceExt;
    device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: bytemuck::cast_slice(data),
        usage: wgpu::BufferUsages::STORAGE
            | wgpu::BufferUsages::COPY_SRC
            | if writable {
                wgpu::BufferUsages::COPY_DST
            } else {
                wgpu::BufferUsages::empty()
            },
    })
}

/// The 96-byte hash input for a golden case, as 24 little-endian u32 words
/// (header bytes followed by the 64-byte big-endian nonce).
fn golden_input_words(case: &GoldenCase) -> [u32; 24] {
    let header = decode_header(case);
    let nonce_be = U512::from(case.nonce).to_big_endian();
    let mut bytes = [0u8; 96];
    bytes[..32].copy_from_slice(&header);
    bytes[32..].copy_from_slice(&nonce_be);
    let mut words = [0u32; 24];
    for i in 0..24 {
        words[i] = u32::from_le_bytes(bytes[i * 4..(i + 1) * 4].try_into().unwrap());
    }
    words
}

fn words_to_bytes(words: &[u32]) -> Vec<u8> {
    words.iter().flat_map(|w| w.to_le_bytes()).collect()
}

/// Golden test of the full hash inside the shader: poseidon2_hash_squeeze_twice
/// must be byte-identical to the canonical CPU hash for every golden case.
#[test]
fn golden_shader_full_hash() {
    let Some(h) = shader_harness() else {
        eprintln!("no GPU adapter, skipping golden_shader_full_hash");
        return;
    };

    let entry = format!(
        "{}

@group(0) @binding(0) var<storage, read> hash_inputs: array<u32>;
@group(0) @binding(1) var<storage, read_write> hash_outputs: array<u32>;

@compute @workgroup_size(1)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{
    var input: array<u32, 24>;
    for (var i = 0u; i < 24u; i++) {{
        input[i] = hash_inputs[gid.x * 24u + i];
    }}
    let out = poseidon2_hash_squeeze_twice(input);
    for (var i = 0u; i < 16u; i++) {{
        hash_outputs[gid.x * 16u + i] = out[i];
    }}
}}
",
        include_str!("../src/mining.wgsl")
    );

    let mut inputs = Vec::new();
    for case in GOLDEN_CASES {
        inputs.extend_from_slice(&golden_input_words(case));
    }
    let outputs = vec![0u32; GOLDEN_CASES.len() * 16];

    let in_buf = mk_storage(&h.device, &inputs, false);
    let out_buf = mk_storage(&h.device, &outputs, true);
    let result = h.run_hash_shader(&entry, &[(0, in_buf, false), (1, out_buf, true)]);

    for (idx, case) in GOLDEN_CASES.iter().enumerate() {
        let got = words_to_bytes(&result[idx * 16..(idx + 1) * 16]);
        let want = decode_hash(case);
        assert_eq!(
            got, want,
            "shader poseidon2_hash_squeeze_twice mismatch for golden case nonce {}",
            case.nonce
        );
    }
}

/// Golden test of the mining fast path: CPU-precomputed header state +
/// poseidon2_absorb_from_state + both squeezes must reproduce the golden hash.
/// This is exactly the computation the mining kernel performs.
#[test]
fn golden_shader_precomputed_state_path() {
    let Some(h) = shader_harness() else {
        eprintln!("no GPU adapter, skipping golden_shader_precomputed_state_path");
        return;
    };

    let entry = format!(
        "{}

@group(0) @binding(0) var<storage, read> states: array<u32>;
@group(0) @binding(1) var<storage, read> nonce_words_buf: array<u32>;
@group(0) @binding(2) var<storage, read_write> hash_outputs: array<u32>;

@compute @workgroup_size(1)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{
    var st: array<GoldilocksField, 12>;
    for (var i = 0u; i < 12u; i++) {{
        st[i] = GoldilocksField(states[gid.x * 24u + 2u * i], states[gid.x * 24u + 2u * i + 1u]);
    }}
    var nw: array<u32, 16>;
    for (var i = 0u; i < 16u; i++) {{
        nw[i] = nonce_words_buf[gid.x * 16u + i];
    }}
    var state = poseidon2_absorb_from_state(st, nw);
    let first = field_elements_to_bytes(array<GoldilocksField, 4>(
        state[0], state[1], state[2], state[3]
    ));
    poseidon2_permute(&state);
    let second = field_elements_to_bytes(array<GoldilocksField, 4>(
        state[0], state[1], state[2], state[3]
    ));
    for (var i = 0u; i < 8u; i++) {{
        hash_outputs[gid.x * 16u + i] = first[i];
        hash_outputs[gid.x * 16u + 8u + i] = second[i];
    }}
}}
",
        include_str!("../src/mining.wgsl")
    );

    let mut states = Vec::new();
    let mut nonce_words = Vec::new();
    for case in GOLDEN_CASES {
        states.extend_from_slice(&precompute_header_state(&decode_header(case)));
        // The kernel builds nonce_words[i] = input word 8+i of the byte stream,
        // i.e. little-endian u32 groups of the big-endian nonce bytes.
        let nonce_be = U512::from(case.nonce).to_big_endian();
        for i in 0..16 {
            nonce_words.push(u32::from_le_bytes(
                nonce_be[i * 4..(i + 1) * 4].try_into().unwrap(),
            ));
        }
    }
    let outputs = vec![0u32; GOLDEN_CASES.len() * 16];

    let st_buf = mk_storage(&h.device, &states, false);
    let nw_buf = mk_storage(&h.device, &nonce_words, false);
    let out_buf = mk_storage(&h.device, &outputs, true);
    let result = h.run_hash_shader(
        &entry,
        &[(0, st_buf, false), (1, nw_buf, false), (2, out_buf, true)],
    );

    for (idx, case) in GOLDEN_CASES.iter().enumerate() {
        let got = words_to_bytes(&result[idx * 16..(idx + 1) * 16]);
        let want = decode_hash(case);
        assert_eq!(
            got, want,
            "precomputed-state path mismatch for golden case nonce {}",
            case.nonce
        );
    }
}
