//! One-off generator of golden test vectors for tests/gpu_golden.rs.
//! Run: cargo run -p engine-gpu --example gen_golden

use pow_core::{hash_from_nonce, JobContext};
use primitive_types::U512;

fn main() {
    let cases: [([u8; 32], u64); 6] = [
        ([0u8; 32], 0),
        ([1u8; 32], 123456789),
        ([0xABu8; 32], u64::MAX),
        (
            {
                let mut h = [0u8; 32];
                for (i, b) in h.iter_mut().enumerate() {
                    *b = i as u8;
                }
                h
            },
            987654321,
        ),
        ([0xFFu8; 32], 42),
        ([7u8; 32], 1u64 << 40),
    ];

    println!("// Generated by examples/gen_golden.rs using pow_core::hash_from_nonce (canonical qpow-math).");
    println!("pub struct GoldenCase {{");
    println!("    pub header_hex: &'static str,");
    println!("    pub nonce: u64,");
    println!("    pub hash_hex: &'static str,");
    println!("}}");
    println!("pub const GOLDEN_CASES: &[GoldenCase] = &[");
    for (header, nonce) in cases {
        let ctx = JobContext::new(header, U512::from(1u64));
        let hash = hash_from_nonce(&ctx, U512::from(nonce));
        let header_hex = hex::encode(header);
        let hash_bytes = hash.to_big_endian();
        println!("    GoldenCase {{");
        println!("        header_hex: \"{header_hex}\",");
        println!("        nonce: {nonce},");
        println!("        hash_hex: \"{}\",", hex::encode(hash_bytes));
        println!("    }},");
    }
    println!("];");
}
